2021-11-21 05:33:58,426 INFO    MainThread:129712 [wandb_setup.py:_flush():71] setting env: {}
2021-11-21 05:33:58,427 INFO    MainThread:129712 [wandb_setup.py:_flush():71] setting login settings: {}
2021-11-21 05:33:58,427 INFO    MainThread:129712 [wandb_init.py:_log_setup():371] Logging user logs to /sata/code/limestone/wandb/run-20211121_053358-3lbs6ktq/logs/debug.log
2021-11-21 05:33:58,427 INFO    MainThread:129712 [wandb_init.py:_log_setup():372] Logging internal logs to /sata/code/limestone/wandb/run-20211121_053358-3lbs6ktq/logs/debug-internal.log
2021-11-21 05:33:58,428 INFO    MainThread:129712 [wandb_init.py:init():404] calling init triggers
2021-11-21 05:33:58,428 INFO    MainThread:129712 [wandb_init.py:init():409] wandb.init called with sweep_config: {}
config: {}
2021-11-21 05:33:58,429 INFO    MainThread:129712 [wandb_init.py:init():449] starting backend
2021-11-21 05:33:58,429 INFO    MainThread:129712 [backend.py:_multiprocessing_setup():95] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2021-11-21 05:33:58,449 INFO    MainThread:129712 [backend.py:ensure_launched():199] starting backend process...
2021-11-21 05:33:58,455 INFO    MainThread:129712 [backend.py:ensure_launched():204] started backend process with pid: 129721
2021-11-21 05:33:58,457 INFO    MainThread:129712 [wandb_init.py:init():458] backend started and connected
2021-11-21 05:33:58,459 INFO    MainThread:129712 [wandb_init.py:init():519] updated telemetry
2021-11-21 05:33:58,473 INFO    MainThread:129712 [wandb_init.py:init():549] communicating current version
2021-11-21 05:33:59,023 INFO    MainThread:129712 [wandb_init.py:init():554] got version response 
2021-11-21 05:33:59,023 INFO    MainThread:129712 [wandb_init.py:init():564] communicating run to backend with 30 second timeout
2021-11-21 05:33:59,154 INFO    MainThread:129712 [wandb_init.py:init():592] starting run threads in backend
2021-11-21 05:34:00,293 INFO    MainThread:129712 [wandb_run.py:_console_start():1816] atexit reg
2021-11-21 05:34:00,293 INFO    MainThread:129712 [wandb_run.py:_redirect():1690] redirect: SettingsConsole.REDIRECT
2021-11-21 05:34:00,294 INFO    MainThread:129712 [wandb_run.py:_redirect():1695] Redirecting console.
2021-11-21 05:34:00,295 INFO    MainThread:129712 [wandb_run.py:_redirect():1751] Redirects installed.
2021-11-21 05:34:00,295 INFO    MainThread:129712 [wandb_init.py:init():619] run started, returning control to user process
2021-11-21 05:34:00,393 INFO    MainThread:129712 [wandb_run.py:_atexit_cleanup():1786] got exitcode: 1
2021-11-21 05:34:00,393 INFO    MainThread:129712 [wandb_run.py:_restore():1758] restore
2021-11-21 05:34:02,828 INFO    MainThread:129712 [wandb_run.py:_wait_for_finish():1916] got exit ret: file_counts {
  wandb_count: 1
}
pusher_stats {
  uploaded_bytes: 727
  total_bytes: 727
}

2021-11-21 05:34:02,968 INFO    MainThread:129712 [wandb_run.py:_wait_for_finish():1916] got exit ret: file_counts {
  wandb_count: 1
}
pusher_stats {
  uploaded_bytes: 727
  total_bytes: 727
}

2021-11-21 05:34:03,185 INFO    MainThread:129712 [wandb_run.py:_wait_for_finish():1916] got exit ret: file_counts {
  wandb_count: 4
}
pusher_stats {
  uploaded_bytes: 727
  total_bytes: 7470
}

2021-11-21 05:34:03,288 INFO    MainThread:129712 [wandb_run.py:_wait_for_finish():1916] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 727
  total_bytes: 7785
}

2021-11-21 05:34:03,398 INFO    MainThread:129712 [wandb_run.py:_wait_for_finish():1916] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 7444
  total_bytes: 7785
}

2021-11-21 05:34:03,502 INFO    MainThread:129712 [wandb_run.py:_wait_for_finish():1916] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 7785
  total_bytes: 7785
}

2021-11-21 05:34:03,605 INFO    MainThread:129712 [wandb_run.py:_wait_for_finish():1916] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 7785
  total_bytes: 7785
}

2021-11-21 05:34:03,709 INFO    MainThread:129712 [wandb_run.py:_wait_for_finish():1916] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 7785
  total_bytes: 7785
}

2021-11-21 05:34:03,812 INFO    MainThread:129712 [wandb_run.py:_wait_for_finish():1916] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 7785
  total_bytes: 7785
}

2021-11-21 05:34:03,979 INFO    MainThread:129712 [wandb_run.py:_wait_for_finish():1916] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 7785
  total_bytes: 7785
}

2021-11-21 05:34:04,260 INFO    MainThread:129712 [wandb_run.py:_wait_for_finish():1916] got exit ret: done: true
exit_result {
}
file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 7785
  total_bytes: 7785
}
local_info {
}

2021-11-21 05:34:05,549 INFO    MainThread:129712 [wandb_run.py:_append_files():2184] logging synced files
